# Generated by Django 5.1.6 on 2026-02-02 16:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('config_type', models.CharField(choices=[('CLIMATE', 'Climate Data API'), ('SOLAR', 'Solar Analysis API'), ('PRICE', 'Market Price API'), ('GENERAL', 'General API')], default='GENERAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate_limit', models.IntegerField(default=100, help_text='Maximum requests per minute', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('burst_limit', models.IntegerField(default=20, help_text='Burst limit for immediate requests', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('window_seconds', models.IntegerField(default=60, help_text='Time window for rate limiting in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('require_authentication', models.BooleanField(default=False)),
                ('allowed_origins', models.TextField(blank=True, help_text='Comma-separated list of allowed origins for CORS', null=True)),
                ('cors_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, null=True)),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cache_ttl', models.IntegerField(default=300, help_text='Cache time-to-live in seconds', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)])),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('endpoint', models.CharField(max_length=500)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('total_response_time', models.FloatField(default=0, help_text='Total response time in milliseconds')),
                ('avg_response_time', models.FloatField(default=0, help_text='Average response time in milliseconds')),
                ('p95_response_time', models.FloatField(default=0, help_text='95th percentile response time')),
                ('p99_response_time', models.FloatField(default=0, help_text='99th percentile response time')),
                ('min_response_time', models.FloatField(default=0)),
                ('max_response_time', models.FloatField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('peak_hour', models.IntegerField(default=0, help_text='Hour with most requests (0-23)')),
                ('data_transferred', models.BigIntegerField(default=0, help_text='Total data transferred in bytes')),
                ('avg_request_size', models.FloatField(default=0, help_text='Average request size in bytes')),
                ('avg_response_size', models.FloatField(default=0, help_text='Average response size in bytes')),
            ],
            options={
                'verbose_name': 'API Analytics',
                'verbose_name_plural': 'API Analytics',
                'ordering': ['-date', 'endpoint'],
                'indexes': [models.Index(fields=['date'], name='api_apianal_date_084709_idx'), models.Index(fields=['endpoint', 'date'], name='api_apianal_endpoin_18287a_idx')],
                'unique_together': {('date', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.apiconfig')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_apilog_timesta_6da0c7_idx'), models.Index(fields=['endpoint', 'timestamp'], name='api_apilog_endpoin_358768_idx'), models.Index(fields=['status_code', 'timestamp'], name='api_apilog_status__774aee_idx')],
            },
        ),
    ]
