import os
import shutil
from pathlib import Path

def export_presentation_assets():
    """
    Exports the best visual plots and diagrams generated by YOLOv8 
    during training, zipping them up for easy download and presentation.
    """
    print("==================================================")
    print("📊 تجهيز ملفات العرض التقديمي (Presentation Assets)")
    print("==================================================")

    run_dir = Path('/kaggle/working/shamsi-project/runs/segment/shamsi_roof_model')
    export_dir = Path('/kaggle/working/presentation_assets')
    
    if not run_dir.exists():
        print("❌ لم يتم العثور على نتائج التدريب. تأكد أن التدريب انتهى بنجاح.")
        return

    # إنشاء مجلد التصدير
    if export_dir.exists():
        shutil.rmtree(export_dir)
    export_dir.mkdir(parents=True)

    # قائمة بأهم الصور التي ينتجها YOLO والتي تبهر لجان التحكيم
    key_assets = [
        'results.png',                  # منحنيات التعلم والدقة (Loss & mAP)
        'confusion_matrix.png',         # مصفوفة الارتباك (توضح قدرة المودل على التفريق بين الكلاسات)
        'confusion_matrix_normalized.png',
        'val_batch0_labels.jpg',        # الصور الأصلية مع الـ Ground Truth
        'val_batch0_pred.jpg',          # توقعات المودل لنفس الصور أعلاه (مقارنة ممتازة)
        'val_batch1_labels.jpg',
        'val_batch1_pred.jpg',
        'val_batch2_labels.jpg',
        'val_batch2_pred.jpg',
        'F1_curve.png',                 # منحنى F1 Score
        'PR_curve.png'                  # منحنى Precision-Recall
    ]

    copied_count = 0
    for asset in key_assets:
        src_path = run_dir / asset
        if src_path.exists():
            shutil.copy2(src_path, export_dir / asset)
            copied_count += 1
            print(f"✅ تم سحب: {asset}")

    # ضغط المجلد لتسهيل التحميل
    shutil.make_archive('/kaggle/working/presentation_assets', 'zip', export_dir)
    print(f"\n🎉 تم تجميع {copied_count} صورة احترافية للبرزنتيشن!")
    print("الملف جاهز للتحميل: /kaggle/working/presentation_assets.zip")

    try:
        from IPython.display import display, FileLink
        display(FileLink(r'/kaggle/working/presentation_assets.zip'))
        print("اضغط على الرابط أعلاه لتحميل ملف البرزنتيشن! 📥")
    except ImportError:
        pass

if __name__ == '__main__':
    export_presentation_assets()
