# Generated by Django 5.1.7 on 2026-02-18 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Record"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=10)),
                (
                    "centroid_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "centroid_lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("area_sqkm", models.FloatField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Record"),
                ),
                (
                    "location_id",
                    models.IntegerField(
                        help_text="Unique ID from source dataset", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("elevation", models.FloatField(blank=True, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("CITY", "City"),
                            ("STATION", "Solar Station"),
                            ("PROPOSED", "Proposed Site"),
                        ],
                        default="CITY",
                        max_length=50,
                    ),
                ),
                ("avg_solar_radiation", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
                ("solar_potential_score", models.FloatField(blank=True, null=True)),
                (
                    "solar_potential_category",
                    models.CharField(default="UNKNOWN", max_length=20),
                ),
                (
                    "governorate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="solar_data.governorate",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyClimateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Record"),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "allsky_sfc_sw_dwn",
                    models.FloatField(verbose_name="Solar Radiation (kWh/m²/day)"),
                ),
                ("t2m", models.FloatField(verbose_name="Avg Temperature (°C)")),
                ("t2m_max", models.FloatField(null=True)),
                ("t2m_min", models.FloatField(null=True)),
                ("rh2m", models.FloatField(verbose_name="Relative Humidity (%)")),
                ("ws2m", models.FloatField(verbose_name="Wind Speed (m/s)")),
                (
                    "prectotcorr",
                    models.FloatField(default=0, verbose_name="Precipitation (mm)"),
                ),
                (
                    "solar_efficiency_factor",
                    models.FloatField(
                        help_text="Calculated efficiency impact (0-1)", null=True
                    ),
                ),
                (
                    "dust_risk_score",
                    models.FloatField(help_text="Risk of soiling (0-1)", null=True),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_data",
                        to="solar_data.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MonthlySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Record"),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("avg_radiation", models.FloatField()),
                ("avg_temperature", models.FloatField()),
                ("total_precipitation", models.FloatField()),
                (
                    "solar_grade",
                    models.CharField(default="C", help_text="Grade A-F", max_length=2),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_summaries",
                        to="solar_data.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["latitude", "longitude"], name="solar_data__latitud_63e3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["solar_potential_score"], name="solar_data__solar_p_8c8737_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyclimatedata",
            unique_together={("location", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="monthlysummary",
            unique_together={("location", "year", "month")},
        ),
    ]
