# Generated by Django 5.1.6 on 2026-04-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclimatedata',
            name='cloud_amt',
            field=models.FloatField(blank=True, help_text='Cloud amount (%)', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='data_source',
            field=models.CharField(default='NASA_POWER', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='clear_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='days_count',
            field=models.IntegerField(default=30),
        ),
    ]
