# Generated by Django 5.1.7 on 2026-04-25 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0002_dailyclimatedata_cloud_amt_location_data_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_name_ar', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('price_min_egp', models.FloatField()),
                ('price_max_egp', models.FloatField()),
                ('price_avg_egp', models.FloatField()),
                ('governorate', models.CharField(default='Cairo', max_length=50)),
                ('data_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity_kw', models.FloatField()),
                ('inverter_type', models.CharField(choices=[('ON_GRID', 'On-Grid String Inverter'), ('HYBRID', 'Hybrid Inverter'), ('OFF_GRID', 'Off-Grid Inverter'), ('MICRO', 'Micro Inverter')], max_length=20)),
                ('efficiency_pct', models.FloatField()),
                ('warranty_years', models.IntegerField(default=5)),
                ('price_egp', models.FloatField()),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('data_date', models.DateField()),
                ('in_stock', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['capacity_kw', 'price_egp'],
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('capacity_w', models.IntegerField()),
                ('panel_type', models.CharField(max_length=20)),
                ('technology', models.CharField(max_length=50)),
                ('efficiency_pct', models.FloatField()),
                ('temp_coefficient_pct', models.FloatField()),
                ('degradation_rate_pct', models.FloatField(default=0.45)),
                ('warranty_years', models.IntegerField(default=25)),
                ('price_egp', models.FloatField()),
                ('price_per_watt_egp', models.FloatField()),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('governorate', models.CharField(default='Cairo', max_length=50)),
                ('data_date', models.DateField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_per_watt_egp'],
            },
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('available_area_m2', models.FloatField()),
                ('monthly_consumption_kwh', models.FloatField()),
                ('usage_type', models.CharField(max_length=30)),
                ('budget_egp', models.FloatField()),
                ('shading_loss_pct', models.FloatField(default=5.0)),
                ('include_battery', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPTIMIZING', 'Optimizing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('optimization_run_id', models.CharField(blank=True, max_length=20)),
                ('pareto_solutions', models.JSONField(default=list)),
                ('selected_design', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solar_data.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('IRRIGATION_LV', 'Irrigation Low Voltage'), ('OTHER_LV', 'Other Low Voltage'), ('MEDIUM_VOLTAGE', 'Medium Voltage'), ('HIGH_VOLTAGE', 'High Voltage'), ('EXTRA_HIGH_VOLTAGE', 'Extra High Voltage')], max_length=30)),
                ('tier_min_kwh', models.IntegerField()),
                ('tier_max_kwh', models.IntegerField(blank=True, null=True)),
                ('consumption_bracket_min', models.IntegerField(default=0)),
                ('consumption_bracket_max', models.IntegerField(blank=True, null=True)),
                ('price_piasters', models.DecimalField(decimal_places=1, max_digits=6)),
                ('customer_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('effective_date', models.DateField()),
                ('source_url', models.URLField(default='https://egyptera.org/ar/TarrifAug2024.aspx')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['usage_type', 'consumption_bracket_min', 'tier_min_kwh'],
                'indexes': [models.Index(fields=['usage_type', 'consumption_bracket_min'], name='solar_data__usage_t_b8b600_idx')],
            },
        ),
    ]
