# Generated by Django 5.1.7 on 2026-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0004_inverter_electrical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='designproject',
            name='load_input_mode',
            field=models.CharField(default='kwh', max_length=10),
        ),
        migrations.AddField(
            model_name='designproject',
            name='monthly_bill_egp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
